### ISSUE TITLE
Tamir app icon

### ISSUE THREAD

**Issue by EitanOfFun** [EitanOfFun/tamir-app#40]
- Crop and use PNG in basecamp
- Use only Tamir logo (not the text in logo)

**Comment by alanyou73** [comment]
here you want me change the "tamir" on the screen header for the logo ?

**Comment by EitanOfFun** [comment]
Yeah, but without the text on the left of the logo, just the word טמיר



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/27/19,
04:15:14 PM

**Comment by alanyou73** [comment]
done for android
